// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SojasStoreContext))]
    [Migration("20220114212718_FinalSurrender")]
    partial class FinalSurrender
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<int>("InChargeSsn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("InChargeSsn");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 10,
                            InChargeSsn = 1001,
                            Name = "Mejeri"
                        },
                        new
                        {
                            DepartmentId = 11,
                            InChargeSsn = 2001,
                            Name = "Kött"
                        },
                        new
                        {
                            DepartmentId = 12,
                            InChargeSsn = 2001,
                            Name = "Bröd"
                        },
                        new
                        {
                            DepartmentId = 13,
                            InChargeSsn = 1850,
                            Name = "Skafferi"
                        },
                        new
                        {
                            DepartmentId = 14,
                            InChargeSsn = 1001,
                            Name = "Grönsaker"
                        });
                });

            modelBuilder.Entity("DAL.Models.Email", b =>
                {
                    b.Property<string>("Emails")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployeeSsn")
                        .HasColumnType("int");

                    b.HasKey("Emails", "EmployeeSsn");

                    b.HasIndex("EmployeeSsn");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Emails = "erik@gmail.com",
                            EmployeeSsn = 1001
                        },
                        new
                        {
                            Emails = "youngNfab@live.se",
                            EmployeeSsn = 2001
                        },
                        new
                        {
                            Emails = "jjonsson@gmail.com",
                            EmployeeSsn = 2001
                        },
                        new
                        {
                            Emails = "evalarsson@ghotmail.com",
                            EmployeeSsn = 1850
                        },
                        new
                        {
                            Emails = "eva@gmail.com",
                            EmployeeSsn = 1850
                        });
                });

            modelBuilder.Entity("DAL.Models.Employee", b =>
                {
                    b.Property<int>("Ssn")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("MentorSsn")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ssn");

                    b.HasIndex("MentorSsn");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Ssn = 1001,
                            EmployeeId = 1001,
                            Name = "Erik",
                            PhoneNumber = "123-456"
                        },
                        new
                        {
                            Ssn = 2001,
                            EmployeeId = 1002,
                            Name = "Johanna",
                            PhoneNumber = "456-789"
                        },
                        new
                        {
                            Ssn = 1850,
                            EmployeeId = 1003,
                            Name = "Eva",
                            PhoneNumber = "789-123"
                        });
                });

            modelBuilder.Entity("DAL.Models.Ingredients", b =>
                {
                    b.Property<string>("Ingredient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductProductId")
                        .HasColumnType("int");

                    b.HasKey("Ingredient", "ProductProductId");

                    b.HasIndex("ProductProductId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DAL.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("DAL.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BarCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("BestBefore")
                        .HasColumnType("Date");

                    b.Property<int?>("CheckedBySsn")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CheckedBySsn");

                    b.HasIndex("SaleId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 10001,
                            Amount = 2,
                            BarCode = 123456,
                            BestBefore = new DateTime(2022, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 2001,
                            CheckedDate = new DateTime(2021, 12, 30, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mjölk",
                            Price = 13.5
                        },
                        new
                        {
                            ProductId = 10002,
                            Amount = 8,
                            BarCode = 222555,
                            BestBefore = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 1001,
                            CheckedDate = new DateTime(2021, 12, 25, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kaffe",
                            Price = 25.989999999999998
                        },
                        new
                        {
                            ProductId = 10003,
                            Amount = 12,
                            BarCode = 558874,
                            BestBefore = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 1001,
                            CheckedDate = new DateTime(2022, 1, 10, 23, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grädde",
                            Price = 54.200000000000003
                        },
                        new
                        {
                            ProductId = 10004,
                            Amount = 1,
                            BarCode = 654321,
                            BestBefore = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 1001,
                            CheckedDate = new DateTime(2022, 1, 2, 16, 59, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ost",
                            Price = 108.5
                        },
                        new
                        {
                            ProductId = 10005,
                            Amount = 90,
                            BarCode = 258369,
                            BestBefore = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 1850,
                            CheckedDate = new DateTime(2022, 1, 2, 8, 25, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fisk",
                            Price = 81.900000000000006
                        },
                        new
                        {
                            ProductId = 10006,
                            Amount = 15,
                            BarCode = 147258,
                            BestBefore = new DateTime(2022, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckedBySsn = 1850,
                            CheckedDate = new DateTime(2022, 1, 6, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bröd",
                            Price = 25.899999999999999
                        });
                });

            modelBuilder.Entity("DepartmentProduct", b =>
                {
                    b.Property<int>("DepartmentsDepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsProductId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentsDepartmentId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("DepartmentProduct");
                });

            modelBuilder.Entity("DAL.Department", b =>
                {
                    b.HasOne("DAL.Models.Employee", "InCharge")
                        .WithMany("InChargeOf")
                        .HasForeignKey("InChargeSsn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InCharge");
                });

            modelBuilder.Entity("DAL.Models.Email", b =>
                {
                    b.HasOne("DAL.Models.Employee", "Employee")
                        .WithMany("Emails")
                        .HasForeignKey("EmployeeSsn")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DAL.Models.Employee", b =>
                {
                    b.HasOne("DAL.Models.Employee", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorSsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("DAL.Models.Ingredients", b =>
                {
                    b.HasOne("DAL.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DAL.Product", b =>
                {
                    b.HasOne("DAL.Models.Employee", "CheckedBy")
                        .WithMany("Checked")
                        .HasForeignKey("CheckedBySsn")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Models.Sale", "Sale")
                        .WithMany("ProductsOnSale")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CheckedBy");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("DepartmentProduct", b =>
                {
                    b.HasOne("DAL.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentsDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DAL.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Employee", b =>
                {
                    b.Navigation("Checked");

                    b.Navigation("Emails");

                    b.Navigation("InChargeOf");
                });

            modelBuilder.Entity("DAL.Models.Sale", b =>
                {
                    b.Navigation("ProductsOnSale");
                });
#pragma warning restore 612, 618
        }
    }
}
